# swagger/brand.yaml

openapi: 3.0.0
info:
  title: WMS API - Master (Brand)
  description: API endpoints for managing product brands.
  version: 1.0.0
servers:
  - url: http://localhost:7501/api/master
    description: Development server

components:
  schemas:
    Brand:
      type: object
      properties:
        BrandID: { type: integer }
        BrandCode: { type: string }
        BrandName: { type: string }
        ParentBrandID: { type: integer, nullable: true }
        ParentBrandName: { type: string, nullable: true }
        IsActive: { type: boolean }
      required:
        - BrandCode
        - BrandName
        - IsActive

  securitySchemes:
    bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT }

security:
  - bearerAuth: []

paths:
  /brand/addBrand:
    post:
      summary: Add a new brand
      tags: [Brand]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                BrandCode: { type: string }
                BrandName: { type: string }
                ParentBrandID: { type: integer, nullable: true }
                IsActive: { type: boolean }
                user_id: { type: integer }
      responses:
        "201": { description: "Brand created" }

  /brand/updateBrand:
    post:
      summary: Update an existing brand
      tags: [Brand]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                BrandID: { type: integer }
                BrandCode: { type: string }
                BrandName: { type: string }
                ParentBrandID: { type: integer, nullable: true }
                IsActive: { type: boolean }
                user_id: { type: integer }
      responses:
        "200": { description: "Brand updated" }

  /brand/getBrand:
    post:
      summary: Get a single brand by ID
      tags: [Brand]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: { BrandID: { type: integer } }
      responses:
        "200":
          description: OK
          content:
            application/json: { schema: { $ref: "#/components/schemas/Brand" } }

  /brand/getAllBrands:
    post:
      summary: Get a list of all brands (paginated)
      tags: [Brand]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page: { type: integer }
                pageSize: { type: integer }
                search: { type: string, nullable: true }
                sortBy: { type: string, nullable: true }
                sortOrder: { type: string, enum: [asc, desc], nullable: true }
                IsActive: { type: boolean, nullable: true }
      responses:
        "200": { description: "A list of brands." }

  /brand/deleteBrand:
    post:
      summary: Delete a brand
      tags: [Brand]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                BrandID: { type: integer }
                user_id: { type: integer }
      responses:
        "200": { description: "Brand deleted" }

  /brand/getBrandsLite:
    post:
      summary: Get a simplified list of active brands for dropdowns
      tags: [Brand]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                excludeBrandID:
                  type: integer
                  description: Optional. Exclude a specific BrandID from the list (useful for parent selection).
                  nullable: true
      responses:
        "200": { description: OK }
