openapi: 3.0.0
info:
  title: Master Data API - Country
  description: API endpoints for managing countries.
  version: 1.0.0
servers:
  - url: http://localhost:7501/api
    description: Development server

components:
  # ... (The 'components' section with schemas is unchanged)
  schemas:
    Country:
      type: object
      properties:
        CountryID:
          type: integer
          description: The unique auto-incrementing ID of the country.
          example: 101
        CountryName:
          type: string
          example: "India"
        CountryCode:
          type: string
          example: "IN"
        CountryISDCode:
          type: string
          example: "+91"
        CountryCurrency:
          type: string
          example: "INR"
        IsActive:
          type: boolean
          example: true
        IsDeleted:
          type: boolean
          example: false
        CreatedBy:
          type: integer
          example: 1
        UpdatedBy:
          type: integer
          example: 1
        CreatedDate:
          type: string
          format: date-time
        UpdatedDate:
          type: string
          format: date-time
        CreatedByUserName:
          type: string
          example: "admin"
        UpdatedByUserName:
          type: string
          example: "admin"
    Error:
      type: object
      properties:
        error:
          type: string
          description: A message describing the error.
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /master/country/addCountry: # <-- UPDATED PATH
    post:
      tags:
        - Country
      summary: Add a new country
      # ... (rest of the endpoint definition is unchanged)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - CountryName
                - CountryCode
                - CountryISDCode
                - CountryCurrency
                - IsActive
                - user_id
              properties:
                CountryName:
                  type: string
                  example: "United States"
                CountryCode:
                  type: string
                  example: "US"
                CountryISDCode:
                  type: string
                  example: "+1"
                CountryCurrency:
                  type: string
                  example: "USD"
                IsActive:
                  type: boolean
                  example: true
                user_id:
                  type: integer
                  description: The ID of the user performing the action.
                  example: 1
      responses:
        "201":
          description: Country added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/Country"
        "400":
          description: Bad request (e.g., missing fields, duplicates)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /master/country/getAllCountries: # <-- UPDATED PATH
    post:
      tags:
        - Country
      summary: Get a list of all active countries
      # ... (rest of the endpoint definition is unchanged)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                IsActive:
                  type: boolean
                  description: "Optional: filter by active status (true/false)."
                user_id:
                  type: integer
                  description: The ID of the user performing the action.
                  example: 1
      responses:
        "200":
          description: A list of countries
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Country"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /master/country/getCountry: # <-- UPDATED PATH
    post:
      tags:
        - Country
      summary: Get a single country by its ID
      # ... (rest of the endpoint definition is unchanged)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - CountryID
                - user_id
              properties:
                CountryID:
                  type: integer
                  description: The unique ID of the country to retrieve.
                  example: 101
                user_id:
                  type: integer
                  description: The ID of the user performing the action.
                  example: 1
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Country"
        "400":
          description: Country not found or bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /master/country/updateCountry: # <-- UPDATED PATH
    post:
      tags:
        - Country
      summary: Update an existing country
      # ... (rest of the endpoint definition is unchanged)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - CountryID
                - CountryName
                - CountryCode
                - CountryISDCode
                - CountryCurrency
                - IsActive
                - user_id
              properties:
                CountryID:
                  type: integer
                  description: The ID of the country to update.
                  example: 101
                CountryName:
                  type: string
                  example: "United States of America"
                CountryCode:
                  type: string
                  example: "USA"
                CountryISDCode:
                  type: string
                  example: "+1"
                CountryCurrency:
                  type: string
                  example: "USD"
                IsActive:
                  type: boolean
                  example: false
                user_id:
                  type: integer
                  description: The ID of the user performing the action.
                  example: 1
      responses:
        "200":
          description: Country updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/Country"
        "400":
          description: Country not found or bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /master/country/deleteCountry: # <-- UPDATED PATH
    post:
      tags:
        - Country
      summary: Delete a country (soft delete)
      # ... (rest of the endpoint definition is unchanged)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - CountryID
                - user_id
              properties:
                CountryID:
                  type: integer
                  description: The ID of the country to delete.
                  example: 101
                user_id:
                  type: integer
                  description: The ID of the user performing the action.
                  example: 1
      responses:
        "200":
          description: Country deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Country deleted successfully."
        "400":
          description: Country not found or bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
