openapi: 3.0.0
info:
  title: Product Consume Master API
  description: API endpoints for managing Product Consume master data.
  version: 1.0.0
servers:
  - url: /api/master
    description: Development server

components:
  schemas:
    ProductConsume:
      type: object
      properties:
        ProductConsumeID:
          type: integer
          description: Unique identifier for the Product Consume.
        ProductConsumeType:
          type: string
          description: The type or name of the product consumption method.
        ProductConsumeDescription:
          type: string
          description: A detailed description of the Product Consume type.
        IsActive:
          type: boolean
          description: Flag indicating if the record is active.
        CreatedByUserName:
          type: string
        UpdatedByUserName:
          type: string
      required:
        - ProductConsumeType
        - ProductConsumeDescription
        - IsActive

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /product-consume/addProductConsume:
    post:
      summary: Add a new Product Consume type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ProductConsumeType:
                  type: string
                ProductConsumeDescription:
                  type: string
                IsActive:
                  type: boolean
      responses:
        "201":
          description: Product Consume added successfully
  /product-consume/getAllProductConsumes:
    post:
      summary: Get a list of all Product Consume types
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                pageSize:
                  type: integer
                search:
                  type: string
                sortBy:
                  type: string
                sortOrder:
                  type: string
      responses:
        "200":
          description: A list of product consumes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductConsume"
  /product-consume/updateProductConsume:
    post:
      summary: Update an existing Product Consume type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ProductConsumeID:
                  type: integer
                ProductConsumeType:
                  type: string
                ProductConsumeDescription:
                  type: string
                IsActive:
                  type: boolean
      responses:
        "200":
          description: Product Consume updated successfully
  /product-consume/deleteProductConsume:
    post:
      summary: Delete a Product Consume type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ProductConsumeID:
                  type: integer
      responses:
        "200":
          description: Product Consume deleted successfully
  /product-consume/getProductConsumesLite:
    post:
      summary: Get a lightweight list of active Product Consumes
      responses:
        "200":
          description: A lite list of product consumes for dropdowns.
