openapi: 3.0.0
info:
  title: Master Data API - Role
  description: API endpoints for retrieving user roles.
  version: 1.0.0
servers:
  - url: http://localhost:7501/api
    description: Development server
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth: { type: http, scheme: bearer, bearerFormat: JWT }
paths:
  /master/role/getAllRoles:
    post:
      tags: [Role]
      summary: Get a list of all available user roles
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id: { type: integer, example: 1 }
      responses:
        "200":
          description: A list of roles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        RoleID: { type: integer }
                        RoleName: { type: string }
                        RoleDescription: { type: string }
