openapi: 3.0.0
info:
  title: SLOC Master API
  description: API endpoints for managing SLOC (Storage Location) master data.
  version: 1.0.0
servers:
  - url: /api/master
    description: Development server

components:
  schemas:
    Sloc:
      type: object
      properties:
        SlocID:
          type: integer
          description: Unique identifier for the SLOC.
        SlocName:
          type: string
          description: The name of the Storage Location.
        IsActive:
          type: boolean
          description: Flag indicating if the record is active.
        CreatedByUserName:
          type: string
        UpdatedByUserName:
          type: string
      required:
        - SlocName
        - IsActive

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /sloc/addSloc:
    post:
      summary: Add a new SLOC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                SlocName:
                  type: string
                IsActive:
                  type: boolean
      responses:
        "201":
          description: SLOC added successfully
  /sloc/getAllSlocs:
    post:
      summary: Get a list of all SLOCs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                pageSize:
                  type: integer
                search:
                  type: string
                sortBy:
                  type: string
                sortOrder:
                  type: string
      responses:
        "200":
          description: A list of SLOCs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sloc"
  /sloc/updateSloc:
    post:
      summary: Update an existing SLOC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                SlocID:
                  type: integer
                SlocName:
                  type: string
                IsActive:
                  type: boolean
      responses:
        "200":
          description: SLOC updated successfully
  /sloc/deleteSloc:
    post:
      summary: Delete a SLOC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                SlocID:
                  type: integer
      responses:
        "200":
          description: SLOC deleted successfully
  /sloc/getSlocsLite:
    post:
      summary: Get a lightweight list of active SLOCs
      responses:
        "200":
          description: A lite list of SLOCs for dropdowns.
