openapi: 3.0.0
info:
  title: Vehicle Type Master API
  description: API endpoints for managing Vehicle Type master data.
  version: 1.0.0
servers:
  - url: /api/master
    description: Development server

components:
  schemas:
    VehicleType:
      type: object
      properties:
        VehicleTypeID:
          type: integer
        VehicleTypeName:
          type: string
        VehicleCapacityTonnes:
          type: number
          format: decimal
        Length:
          type: number
          format: decimal
          nullable: true
        Breadth:
          type: number
          format: decimal
          nullable: true
        Height:
          type: number
          format: decimal
          nullable: true
        UOMID:
          type: integer
          nullable: true
        UOMName:
          type: string
          nullable: true
        IsActive:
          type: boolean
      required:
        - VehicleTypeName
        - VehicleCapacityTonnes
        - IsActive

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /vehicle-type/addVehicleType:
    post:
      summary: Add a new Vehicle Type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                VehicleTypeName:
                  type: string
                VehicleCapacityTonnes:
                  type: number
                Length:
                  type: number
                Breadth:
                  type: number
                Height:
                  type: number
                UOMID:
                  type: integer
                IsActive:
                  type: boolean
              required:
                - VehicleTypeName
                - VehicleCapacityTonnes
                - IsActive
      responses:
        "201":
          description: Vehicle Type added successfully

  /vehicle-type/getAllVehicleTypes:
    post:
      summary: Get a list of all Vehicle Types
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                pageSize:
                  type: integer
                search:
                  type: string
                sortBy:
                  type: string
                sortOrder:
                  type: string
      responses:
        "200":
          description: A list of vehicle types

  /vehicle-type/updateVehicleType:
    post:
      summary: Update an existing Vehicle Type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                VehicleTypeID:
                  type: integer
                VehicleTypeName:
                  type: string
                VehicleCapacityTonnes:
                  type: number
                Length:
                  type: number
                Breadth:
                  type: number
                Height:
                  type: number
                UOMID:
                  type: integer
                IsActive:
                  type: boolean
              required:
                - VehicleTypeID
                - VehicleTypeName
                - VehicleCapacityTonnes
                - IsActive
      responses:
        "200":
          description: Vehicle Type updated successfully

  /vehicle-type/deleteVehicleType:
    post:
      summary: Delete a Vehicle Type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                VehicleTypeID:
                  type: integer
      responses:
        "200":
          description: Vehicle Type deleted successfully

  /vehicle-type/getVehicleTypesLite:
    post:
      summary: Get a lightweight list of active Vehicle Types
      responses:
        "200":
          description: A lite list of vehicle types for dropdowns.
